project:
  type: website

website:
  title: "ISSS624"
  navbar:
    left: 
      - text: Hands-on Exercises
        menu:
          - text: Hands-on Exercise 1
            href: Hands-on_Ex01/Hands-on_Ex01.qmd
          - text: Hands-on Exercise 2
            href: Hands-on_Ex02/Hands-on_Ex02.qmd
          - text: Hands-on Exercise 3
            href: Hands-on_Ex03/Hands-on_Ex03.qmd
          - text: Hands-on Exercise 4
            href: Hands-on_Ex04/Hands-on_Ex04.qmd
          - text: Hands-on Exercise 5
            href: Hands-on_Ex05/Hands-on_Ex05.qmd  
            
           
    
      - text: Take-home Exercises
        menu:
        - text: Take-home Exercise 1
          href: Take-home_Ex01/Take-home_Ex01.qmd
      
    right:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

